name: ML CD Pipeline

on:
  workflow_run:
    workflows: ["ML CI Pipeline"]
    types: [completed]

jobs:
  run_cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Monitoring
        run: python monitor.py

      - name: Run Drift Detection
        run: python drift_detect.py

      - name: Done
        run: echo "CD Pipeline Success ✅"
